### ISSUE TITLE
请问我想给组件再次添加样式该怎么写

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#10]
比如 我想给 ClSelect 组件添加个 padding-right 让她离右面有一些距离，从而和其他的 Input 看起来比较对其，但是我发现 ClSelect 没发加 className, 于是 我尝试外面包一层 View 设置 View 的样式，但是那样的效果却成外距了

`
        <View className='region'>
          <ClSelect title='省份' mode='selector' selector={{ range: this.state.region, rangeKey: 'value' }} />
        </View>
`

**Comment by yinLiangDream** [comment]
不好意思有点忙没看到哈。
想要更改里面的元素，外围可以包裹一层View，并设置 className
然后写入
```scss
.你的className {
  .cu-form-group {
    padding-right: xxx;
  }
}
```

例如：
```jsx
<View className='region'>
  <ClSelect title='省份' mode='selector' selector={{ range: this.state.region, rangeKey: 'value' }} />
</View>
```
```scss
.region {
  .cu-form-group {
    padding-right: xxx;
  }
}
```
通过小程序调试工具可以看到组件库具体的样式名
![image](https://user-images.githubusercontent.com/24502330/65229797-74a50c00-daff-11e9-9178-852638660150.png)
![image](https://user-images.githubusercontent.com/24502330/65229882-8dadbd00-daff-11e9-985c-fd6c8b64a262.png)

为了防止修改全局的 css，所以需要包裹着一层 View，并设置自己的 className
