### ISSUE TITLE
请问  colorui 的 className 怎么用

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#26]
![image](https://user-images.githubusercontent.com/11585188/67266313-80ab3180-f4e2-11e9-8bd1-b07489827737.png)
我见新加了 className 我想通过她去定位控件，从而改变 输入框后面图标的大小 和 跟后面按钮的间距

![image](https://user-images.githubusercontent.com/11585188/67266366-acc6b280-f4e2-11e9-8f9b-eb0ee073226e.png)

```scss
.Heshu{
    .cuIcon-close{
        font-size: 12PX;
    }
}
```
发现并没有生效

**Comment by yinLiangDream** [comment]
`font-size` 大小可以通过 `icon` 属性的 `size` 属性控制，`icon` 属性可以传递 `Icon` 组件的任何属性。

因为`icon` 组件的 `size` 是动态的，所以我将他写在 `style` 里，根据 `CSS 权重` `className` 是不能覆盖的，如果还是想用 `className` 改变 `font-size`，可以加上` !important`。
```scss
.Heshu{
  .cuIcon-close{
      font-size: 12PX !important;
  }
}
```
<img width="674" alt="图片" src="https://user-images.githubusercontent.com/24502330/67354880-52802d00-f588-11e9-80d1-0a118b461a08.png">
<img width="379" alt="图片" src="https://user-images.githubusercontent.com/24502330/67354912-69bf1a80-f588-11e9-9895-3e0421ae30c6.png">

你也可以通过组内内置的 size 来控制：
```jsx
<ClInput className='Heshu' icon={{ iconName: 'close', size: 24 }} />
```
这个 size 会根据屏幕分辨率自动换算成对应的 px
