### ISSUE TITLE
使用Tabs时, 两个分页内容都会显示在页面上

### ISSUE THREAD

**Issue by anonymous-qsh** [yinLiangDream/mp-colorui#72]
## 问题描述

在使用tabs的时候, 切换到第二个显示有问题

截图链接: https://s2.ax1x.com/2020/03/10/8Cdq10.png

## 环境代码

1. `mp-colorui` 的版本号: **v0.6.9**
2. 标明 `Taro` 的版本号: **v2.0.5**
3. 使用代码:

```ts
import { ComponentClass } from 'react';
import Taro, { Component, Config as TaroConfig } from '@tarojs/taro';
import { ClTabs } from "mp-colorui"
import { View } from '@tarojs/components';

import './index.less'

// @ts-ignore
const regeneratorRuntime = global.regeneratorRuntime


type PageStateProps = {}

type PageOwnProps = {}

type IProps = PageStateProps & PageOwnProps

interface Index {
  props: IProps;
}


const verbTabs = [
  {
    text: "最新",
    id: "new"
  },
  {
    text: "排行",
    id: "rank"
  },
];

class Index extends Component {

  componentWillMount(): void {
  }

  config: TaroConfig = {
    navigationBarTitleText: 'DEMO',
    enablePullDownRefresh: true,
  };

  render() {

    return (
      <View>
        <View className='tabs'>
          <ClTabs tabs={verbTabs} type='verb'>
            {verbTabs.map(x => (
              <View key={x.id} id={x.id} style={{ backgroundColor: '#F1F1F1' }}>
                {/*{this.renderTabContent(x.id)}*/}
                {x.id === 'new' && <View className='list'>
                  <View className='item'>
                    233333
                  </View>
                  <View className='item'>
                    233333
                  </View>
                </View>}
                {x.id === 'rank' && <View>
                  22333333333333333333
                </View>}
              </View>
            ))}
          </ClTabs>
        </View>
      </View>
    )
  }
}

export default Index as ComponentClass;
```

```css
.tabs {
  background-color: white;
  margin-top: 4px;
}

.list {
  .bodyView {
    position: relative;
    overflow: visible;
    will-change: transform;
    transform: translate3d(0, 0, 0);
    backface-visibility: hidden;
  }

  .containView {
    position: relative;
  }

  .item {
    height: 200px;
    background-color: aqua;
    margin-top: 4px;
  }

  .loading, .loaded {
    text-align: center;
    font-size: 24px;
    padding: 12px;
    //animation: loading infinite 1000ms ease;
  }
}
```
